# Generated by Django 3.2.3 on 2021-05-28 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PV', models.CharField(blank=True, max_length=100, null=True)),
                ('OS', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('detalhamento', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('vendedor', models.CharField(blank=True, max_length=200, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.cliente')),
                ('executante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='ServicoVenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_servico', models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True)),
                ('Valor_deslocamento', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao_venda', models.CharField(blank=True, max_length=100, null=True)),
                ('preco_servico', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('preco_venda', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('adicional', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('filtro_desloc', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('filtro_serv', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('HT', models.FloatField(default=0)),
                ('QTD', models.IntegerField(default=0)),
                ('HE', models.FloatField(default=0)),
                ('HE_percentual', models.FloatField(default=0)),
                ('AN', models.FloatField(default=0)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.servico')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.vendas')),
            ],
            options={
                'verbose_name': 'Venda ',
                'verbose_name_plural': 'Vendas ',
            },
        ),
    ]
